# Logo Url
# Please enter the absolute path to your logo file
# or remove the following line with replacing logo-header.png with your own logo
logo: /logo-salty-egg.png

# Header
menu:
  Home: /
  # Delete this row if you don't want categories in your header nav bar
  Categories:
  LeetCode: /LeetCode/
  About: /about/

# Article list grouped by year
groupByYear: false

# Content
fancybox: true

# Thumbnail
thumbnail: false

# Scroll Loading
scrollLoading: true

# Sidebar
sidebar: right # sidebar's position (left or right)
email: i@hzhou.me
social_links:
  linkedin: https://www.linkedin.com/in/sbzhouhao/
  github: https://github.com/zhouhao
  weibo: http://www.weibo.com/sbzhouhao/
  rss: /atom.xml
widgets:
- recent_posts
- tagcloud
- category
#- archive
- links

# Links
links:
  MIT-CHIEF: http://mitchief.org
  "WPILIFE (WPI CSSA)": http://wpilife.org

# Don't Use Google APIs if you are in google-blocked areas
use_google_apis: true

# Miscellaneous
#google_analytics: UA-39886095-1
favicon: /favicon.png
fb_admins:
fb_app_id:
