# Header
menu:
  LeetCode: /LeetCode
  About: /about
  RSS: /atom.xml

# Content
excerpt_link: Read More
prev: Prev
next: Next
fancybox: true

# Sidebar
widgets:
- search
- about
- recent_posts
- archive
- category
- tagcloud

# Miscellaneous
google_analytics:
disqus_shortname: zhouhao
rss: /atom.xml
favicon: /favicon.png
subtitle: "Laugh, you should try; cry, you should try"
